config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :strikes

  root 'welcome#index'

end

app/models/strike.rb
class Strike < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/strikes_controller.rb
class StrikesController < ApplicationController

    def create
        @strikes = Strike.new(strike_params)
        @strikes.save
        redirect_to "/strikes"
    end

    def index
        @strikes = Strike.all
    end

    def new
    end

    def show
        @strike = Strike.find(params[:id])
    end

    private
    def strike_params
        params.require(:strike).permit(:score_a, :score_b, :bat, :ball)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/strikes_helper.rb
module StrikesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skogsbrannboll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/strikes/_display.html.erb
<% @strikes.each do |strike| %>
    <tr>
        <td><%= strike.score_a %></td>
        <td><%= strike.score_b %></td>
        <td><%= strike.bat %></td>
        <td><%= strike.ball %></td>
    </tr>
<% end %>

app/views/strikes/_form.html.erb
<%= form_for :strike, url: strikes_path do |f| %>
    <tr>
        <td><!--<%= f.label :score_a %><br />-->
    <%= f.number_field :score_a %></td>
<td><!--<%= f.label :score_b %><br />-->
    <%= f.number_field :score_b %></td>
<td><!--<%= f.label :bat %><br />-->
    <%= f.text_field :bat %></td>
<td><!--<%= f.label :ball %><br />-->
    <%= f.text_field :ball %></td>
    </tr>
    <tr><td><%= f.submit %></td></tr>
<% end %>

app/views/strikes/index.html.erb
<table>
    <tr>
        <td>Score A</td>
        <td>Score B</td>
        <td>Bat</td>
        <td>Ball</td>
    </tr>
    <%= render 'display' %>
    <%= render 'form' %>
</table>

app/views/strikes/new.html.erb
<table>
    <%= render 'form' %>
</table>

app/views/strikes/show.html.erb
<%= @strike.score_a %> vs <%= @strike.score_b %> <br />
<%= @strike.ball %> vs <%= @strike.bat %>

app/views/welcome/index.html.erb
<h1>Skogsbrännboll!</h1>